# Generated by Django 3.2.11 on 2022-02-13 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('day', models.CharField(choices=[('M', 'Понедельник'), ('Tu', 'Вторник'), ('W', 'Среда'), ('Th', 'Четверг'), ('F', 'Пятница')], default='M', max_length=15)),
                ('start_time', models.TimeField(default=datetime.time(18, 34, 26, 394696))),
                ('end_time', models.TimeField(default=datetime.time(18, 34, 26, 394712))),
                ('week_type', models.CharField(choices=[('NUM', 'Числитель'), ('DEN', 'Знаменатель')], default='NUM', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shcool', models.CharField(max_length=150)),
                ('auditorium', models.IntegerField(max_length=15)),
                ('school_subject', models.ManyToManyField(related_name='group', to='journal.School_subject')),
                ('student', models.ManyToManyField(related_name='group', to='accounts.Student')),
                ('teachers', models.ManyToManyField(related_name='group', to='accounts.Teacher')),
            ],
        ),
    ]
