# Generated by Django 3.2.9 on 2021-11-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('day', models.CharField(choices=[('M', 'Понедельник'), ('Tu', 'Вторник'), ('W', 'Среда'), ('Th', 'Четверг'), ('F', 'Пятница')], default='M', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Turnout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('school_subject', models.ManyToManyField(related_name='turnout', to='journal.School_subject')),
                ('student', models.ManyToManyField(related_name='turnout', to='journal.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shcool', models.CharField(max_length=150)),
                ('school_subject', models.ManyToManyField(related_name='group', to='journal.School_subject')),
                ('teachers', models.ManyToManyField(related_name='group', to='journal.Teacher')),
            ],
        ),
    ]
