# Generated by Django 4.0.1 on 2022-01-05 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_subject',
            name='time',
            field=models.TimeField(default=datetime.time(19, 3, 16, 738248)),
        ),
        migrations.AddField(
            model_name='school_subject',
            name='week_type',
            field=models.CharField(choices=[('NUM', 'Числитель'), ('DEN', 'Знаменатель')], default='NUM', max_length=15),
        ),
    ]
