# Generated by Django 4.0.1 on 2022-01-05 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_school_subject_classroom_alter_school_subject_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_subject',
            name='time',
            field=models.TimeField(default=datetime.time(19, 23, 30, 519867)),
        ),
    ]
