# Generated by Django 4.0.1 on 2022-01-06 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('journal', '0004_alter_school_subject_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shcool', models.CharField(max_length=150)),
                ('auditorium', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='school_subject',
            name='time',
            field=models.TimeField(default=datetime.time(11, 18, 47, 109516)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='group',
            name='school_subject',
            field=models.ManyToManyField(related_name='group', to='journal.School_subject'),
        ),
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(related_name='group', to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(related_name='group', to='accounts.Teacher'),
        ),
    ]
