# Generated by Django 4.0.1 on 2022-01-06 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_group_alter_school_subject_time_delete_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_subject',
            name='time',
            field=models.TimeField(default=datetime.time(11, 19, 8, 24125)),
        ),
    ]
