# Generated by Django 3.2.11 on 2022-01-07 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_school_subject_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_subject',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='school_subject',
            name='time',
        ),
        migrations.AddField(
            model_name='school_subject',
            name='end_time',
            field=models.TimeField(default=datetime.time(14, 7, 24, 407360)),
        ),
        migrations.AddField(
            model_name='school_subject',
            name='start_time',
            field=models.TimeField(default=datetime.time(14, 7, 24, 407343)),
        ),
    ]
