# Generated by Django 4.0.1 on 2022-01-08 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20220107_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_subject',
            name='day',
        ),
        migrations.RemoveField(
            model_name='school_subject',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='school_subject',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='school_subject',
            name='week_type',
        ),
        migrations.AddField(
            model_name='group',
            name='day',
            field=models.CharField(choices=[('M', 'Понедельник'), ('Tu', 'Вторник'), ('W', 'Среда'), ('Th', 'Четверг'), ('F', 'Пятница')], default='M', max_length=15),
        ),
        migrations.AddField(
            model_name='group',
            name='end_time',
            field=models.TimeField(default=datetime.time(15, 56, 1, 462781)),
        ),
        migrations.AddField(
            model_name='group',
            name='start_time',
            field=models.TimeField(default=datetime.time(15, 56, 1, 462764)),
        ),
        migrations.AddField(
            model_name='group',
            name='week_type',
            field=models.CharField(choices=[('NUM', 'Числитель'), ('DEN', 'Знаменатель')], default='NUM', max_length=15),
        ),
    ]
