# Generated by Django 4.0.1 on 2022-01-08 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_remove_school_subject_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(default=datetime.time(15, 56, 9, 633379)),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.TimeField(default=datetime.time(15, 56, 9, 633364)),
        ),
    ]
