# Generated by Django 4.0.1 on 2022-01-08 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_alter_group_end_time_alter_group_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='school_subject',
        ),
        migrations.RemoveField(
            model_name='group',
            name='student',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teachers',
        ),
        migrations.AddField(
            model_name='school_subject',
            name='group',
            field=models.ManyToManyField(related_name='school_subject', to='journal.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 32, 26, 287738)),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.TimeField(default=datetime.time(17, 32, 26, 287721)),
        ),
    ]
