# Generated by Django 4.0.1 on 2022-01-08 17:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_remove_group_school_subject_remove_group_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 56, 44, 756861)),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.TimeField(default=datetime.time(17, 56, 44, 756846)),
        ),
        migrations.RemoveField(
            model_name='school_subject',
            name='group',
        ),
        migrations.AddField(
            model_name='school_subject',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.group'),
        ),
    ]
