# Generated by Django 4.0.1 on 2022-01-08 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_alter_group_end_time_alter_group_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_subject',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='school_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.school_subject'),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 58, 15, 739225)),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.TimeField(default=datetime.time(17, 58, 15, 739201)),
        ),
    ]
