# Generated by Django 4.0.1 on 2022-01-08 17:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_student_group_remove_teacher_group'),
        ('journal', '0012_remove_school_subject_group_group_school_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 59, 51, 789521)),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.TimeField(default=datetime.time(17, 59, 51, 789504)),
        ),
    ]
