# Generated by Django 4.0.1 on 2022-01-08 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_student_group_remove_teacher_group'),
        ('journal', '0013_group_teacher_alter_group_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='student', to='accounts.Teacher'),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 19, 58, 359038)),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.TimeField(default=datetime.time(18, 19, 58, 359023)),
        ),
    ]
