# Generated by Django 4.0.1 on 2022-01-08 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_student_group_remove_teacher_group'),
        ('journal', '0014_group_students_alter_group_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 31, 49, 989774)),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.TimeField(default=datetime.time(18, 31, 49, 989753)),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='student', to='accounts.Student'),
        ),
    ]
