# Generated by Django 4.0.1 on 2022-01-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_alter_group_end_time_alter_group_start_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
