# Generated by Django 3.2.11 on 2022-01-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_auto_20220110_1328'),
        ('journal', '0016_auto_20220117_1148'),
    ]

    operations = [
    ]
