# Generated by Django 3.2.11 on 2022-01-17 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_merge_0011_auto_20220110_1328_0016_auto_20220117_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_subject',
            name='end_time',
            field=models.TimeField(default=datetime.time(14, 14, 52, 649247)),
        ),
        migrations.AlterField(
            model_name='school_subject',
            name='start_time',
            field=models.TimeField(default=datetime.time(14, 14, 52, 649230)),
        ),
    ]
