# Generated by Django 3.2.11 on 2022-01-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='remains',
        ),
    ]
