# Generated by Django 3.2.11 on 2022-01-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_warehouse_remains'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
