# Generated by Django 3.2.11 on 2022-01-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_delete_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='quantity',
            new_name='remains',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='data',
            field=models.DateField(),
        ),
    ]
