# Generated by Django 3.2.11 on 2022-01-17 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20220108_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='extradition',
            name='type',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='data',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='type',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='slug',
            field=models.SlugField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.category'),
        ),
    ]
