# Generated by Django 3.2.11 on 2022-01-10 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20220108_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='data',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='type',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2022, 1, 10, 13, 28, 16, 361349, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='category',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='warehouse.category'),
        ),
    ]
