# Generated by Django 4.0.1 on 2022-01-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_remove_group_school_subject_remove_group_student_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(related_name='student', to='journal.Group'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.ManyToManyField(related_name='teacher', to='journal.Group'),
        ),
    ]
