# Generated by Django 4.0.1 on 2022-01-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_group_teacher_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='group',
        ),
    ]
