# Generated by Django 4.0.1 on 2022-01-08 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_delete_group'),
        ('accounts', '0003_remove_student_group_remove_teacher_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shcool', models.CharField(max_length=150)),
                ('auditorium', models.IntegerField(max_length=15)),
                ('day', models.CharField(choices=[('M', 'Понедельник'), ('Tu', 'Вторник'), ('W', 'Среда'), ('Th', 'Четверг'), ('F', 'Пятница')], default='M', max_length=15)),
                ('start_time', models.TimeField(default=datetime.time(18, 48, 47, 123584))),
                ('end_time', models.TimeField(default=datetime.time(18, 48, 47, 123597))),
                ('week_type', models.CharField(choices=[('NUM', 'Числитель'), ('DEN', 'Знаменатель')], default='NUM', max_length=15)),
                ('school_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.school_subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.group'),
        ),
    ]
