# Generated by Django 4.0.1 on 2022-01-08 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_group_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 54, 2, 206906)),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.TimeField(default=datetime.time(18, 54, 2, 206893)),
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(null=True, to='accounts.Group'),
        ),
    ]
